# Generated by Django 3.1.6 on 2021-03-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0001_auth_user_app_migrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pic',
            new_name='profile_pics',
        ),
    ]
